### ISSUE TITLE
Class based components to functional components

### ISSUE THREAD

**Issue by abhishekshree** [AUV-IITK/auv-iitk.github.io#125]
Need to change `ContactUsPage`, `BlogsPage`, `SingleBlog`
- [x] `SingleBlog`
- [x] `BlogsPage`
- [x] `ContactUsPage`

**Comment by OgunmisiM** [comment]
i can help fix this. Kindly assign to me

**Comment by abhishekshree** [comment]
@OgunmisiM go ahead

**Comment by silvina-varela** [comment]
Is this issue up for grabs?

**Comment by abhishekshree** [comment]
Yes @silvina-varela, you can take this up if you like.

**Comment by abhishekshree** [comment]
any update? @silvina-varela

**Comment by sammaji** [comment]
Hey, is this project actively maintained? If yes, can I work on this issue?

**Comment by sammaji** [comment]
Hey @abhishekshree is this repository still active??

**Comment by abhishekshree** [comment]
yes

**Comment by abhishekshree** [comment]
@everyone, if you feel like working on this PR, please create a pull request and ask me for a review.

**Comment by sammaji** [comment]
ok I'll start working on it, assign me @abhishekshree

**Comment by abhishekshree** [comment]
Go ahead @samyabrata-maji

**Comment by sammaji** [comment]
@abhishekshree please review the PR

**Comment by Hagane3** [comment]
@abhishekshree Please review PR #130

**Comment by Sachin24704** [comment]
Hey, is the issue resolved or still it persists?

**Comment by abhishekshree** [comment]
I think we have one remaining component

> Hey, is the issue resolved or still it persists?

**Comment by Sachin24704** [comment]
@abhishekshree Please review the PR

**Comment by abhishekshree** [comment]
closing issue, all the tasks completed
