### ISSUE TITLE
Update the styling of subsystems subheading under Team overview

### ISSUE THREAD

**Issue by abhishekshree** [AUV-IITK/auv-iitk.github.io#132]
The problem is in http://auv-iitk.github.io/#/team, where the subsystem description is too ugly and does not fit with the theme of the whole website. That particular area is unresponsive as well. Needs a fix.

![image](https://github.com/AUV-IITK/auv-iitk.github.io/assets/25745900/0ed9e2af-da09-4d23-b443-7125f485ddac)

**Comment by vishalsingh2972** [comment]
can you elaborate.....any specific changes or additions that you want so that I can give it a try!

**Comment by abhishekshree** [comment]
as of now, it is pretty ugly and unresponsive, see I expected a layout in which the four cards are neatly arranged and seem important. Like you can see anyone can ignore it with the current design. I'd say fixing the design would be a good start

**Comment by abhishekshree** [comment]
Also note that the content that we already have should be there, no extra addition required content wise

**Comment by vishalsingh2972** [comment]
@abhishekshree can you assign this to me or should I directly send a pull request with the changes?

**Comment by abhishekshree** [comment]
did that, you can send a PR, thanks!

**Comment by vishalsingh2972** [comment]
@abhishekshree could you check PR https://github.com/AUV-IITK/auv-iitk.github.io/pull/133

**Comment by abhishekshree** [comment]
done, you can request for review on the PR itself

**Comment by akshayhere3001** [comment]
I've understand the issue closely, Please assign it to me!

**Comment by abhishekshree** [comment]
sure @akshayhere3001 go ahead

**Comment by trana5197** [comment]
Hi @abhishekshree I can try and make the design better and make it responsive if no one is currently working on it. Can you assign it to me?

**Comment by abhishekshree** [comment]
Definitely, go ahead!

**Comment by trana5197** [comment]
@abhishekshree when I type command: " npm i " its showing this error. Can you help me figure it?
![npm i error](https://github.com/AUV-IITK/auv-iitk.github.io/assets/92117730/a6415dbd-8aec-4688-9d51-a890376fe4c8)

**Comment by abhishekshree** [comment]
use nvm and use node 16 LTS

**Comment by trana5197** [comment]
Done @abhishekshree lemme know if anything else is needed. Thank you.

**Comment by trana5197** [comment]
@abhishekshree please check my PR and lemme know if there are any changes needed. Thank you.
