### ISSUE TITLE
Blinking of message box when clicked on it

### ISSUE THREAD

**Issue by Mayankm96** [AUV-IITK/auv-iitk.github.io#70]
In the Contact Us page, when the message box is clicked the `Message` disappears for a while. 

![er](https://user-images.githubusercontent.com/12863862/35607945-daa73fe0-067c-11e8-8314-76cdc26964f6.png)

**Comment by Mayankm96** [comment]
@umeshmeena141 This issue still persists. Any idea?

**Comment by Ddevendra** [comment]
website framework upgraded
